"""Canonical cross-language verifier for the BurnBar HPKE **v3** relay wrap.

This is the vector lane's stop-condition suite. It loads the canonical fixture
``tests/gateway/fixtures/BurnBarHpkeV3Vector.json`` (regenerate with
``python -m tests.gateway.vectors.generate_burnbar_hpke_v3_vectors``) and proves:

* every positive case's HPKE wrap opens to the expected content key under the
  PINNED sender key, and the sealed payload opens to the expected plaintext;
* inbound event / model_switch payloads carry the strict ``destinationId`` +
  ``replayCounter``/``eventCounter`` schema the production adapter enforces;
* every negative mutation (forgery, tamper, downgrade, stripped marker) is
  rejected fail-closed;
* the fixture metadata is the frozen v3 contract and every authenticated field
  is inspectable;
* the production ``gateway/crypto/relay_e2ee.py`` HPKE primitives are
  byte-identical to the reference, and — once the Python lane lands a public v3
  open — that it opens these exact vectors (auto-detected; skips with an
  actionable reason until then).

The fixture is generated by an independent RFC 9180 reference
(``tests/gateway/vectors/hpke_v3_reference.py``); Swift CryptoKit opens the same
fixture in ``BurnBarHpkeV3CrossPlatformVectorTests.swift`` — three independent
implementations agreeing is the cross-language proof.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

import pytest
from cryptography.exceptions import InvalidTag

from tests.gateway.vectors import hpke_v3_reference as ref

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "BurnBarHpkeV3Vector.json"

REQUIRED_POSITIVES = {
    "phone_event_text",
    "phone_event_model_switch",
    "agent_reply_text",
    "agent_reply_attachment_manifest",
    "agent_reply_attachment_body_key",
}
REQUIRED_NEGATIVES = {
    "wrong_pinned_sender_key",
    "wrong_recipient_key",
    "wrong_key_aad",
    "mutated_enc",
    "mutated_wrapped_key",
    "version_changed_to_2",
    "version_changed_to_1",
    "missing_enc",
    "missing_relay_encryption",
}
# Event-shaped kinds whose opened payload must satisfy the strict inbound schema.
_EVENT_KINDS = {"event", "model_switch"}
_JSON_DESTINATION_KINDS = {"event", "model_switch", "message", "attachment_manifest"}
_REPLAY_KEYS = ("replayCounter", "eventCounter")


def _load() -> dict:
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


FIXTURE = _load()
CASES = {c["name"]: c for c in FIXTURE["cases"]}
POSITIVES = [c for c in FIXTURE["cases"] if c["expected"] == "open"]
NEGATIVES = [c for c in FIXTURE["cases"] if c["expected"] == "reject"]


def _b64d(value: str) -> bytes:
    return base64.b64decode(value, validate=True)


# ---------------------------------------------------------------------------
# Reference self-test + fixture metadata (the frozen contract)
# ---------------------------------------------------------------------------


def test_reference_matches_rfc9180_known_answer_vector():
    """The reference reproduces the canonical RFC 9180 Appendix-A vector for the
    exact shipped suite (P-256 / HKDF-SHA256 / AES-256-GCM / mode_auth) — enc,
    shared_secret, key, base_nonce, and ciphertext all byte-match the RFC."""
    ref.run_rfc9180_kat()


def test_reference_self_test_passes():
    """The RFC 9180 reference round-trips and rejects every forgery class."""
    ref.run_self_test()


def test_fixture_is_the_frozen_v3_contract():
    assert FIXTURE["schemaVersion"] == 1
    assert FIXTURE["relayKeyVersion"] == 3
    assert FIXTURE["relayEncryption"] == "hpke-auth-p256-hkdfsha256-aes256gcm"
    suite = FIXTURE["suite"]
    assert suite["mode"] == "auth"
    assert (suite["kemId"], suite["kdfId"], suite["aeadId"], suite["modeId"]) == (
        0x0010,
        0x0001,
        0x0002,
        0x02,
    )
    assert FIXTURE["hpke"]["infoPrefix"] == "OpenBurnBar-HermesRelay-HPKE-v3|"
    # A reviewer must be able to regenerate it and find every authenticated field.
    assert FIXTURE["generator"]["command"]
    keys = FIXTURE["keys"]
    for required in (
        "agentRecipientPublicKeyX963",
        "agentRecipientPrivateKeyRaw",
        "phoneSenderPublicKeyX963",
        "phoneSenderPrivateKeyRaw",
    ):
        assert keys.get(required), f"missing fixture key material: {required}"


def test_fixture_has_every_required_case():
    assert REQUIRED_POSITIVES <= {c["name"] for c in POSITIVES}
    assert REQUIRED_NEGATIVES <= {c["name"] for c in NEGATIVES}


def test_every_authenticated_field_is_identifiable():
    """Vector-agent stop condition: a reviewer can inspect the JSON and identify
    every authenticated field (the HPKE info, key_aad, enc, wrappedKey, and the
    payload AAD that binds the sealed plaintext)."""
    for case in POSITIVES:
        for field in ("keyAAD", "info", "enc", "wrappedKey", "payloadAAD", "plaintextContentKey"):
            assert case.get(field), f"{case['name']} is missing inspectable field {field}"
        # info is exactly the prefixed key_aad — the binding is visible, not opaque.
        assert case["info"] == "OpenBurnBar-HermesRelay-HPKE-v3|" + case["keyAAD"]


# ---------------------------------------------------------------------------
# Positive cases: open the content key + the sealed payload, check strict schema
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("case", POSITIVES, ids=[c["name"] for c in POSITIVES])
def test_positive_case_opens_with_pinned_sender(case):
    enc, wrapped = ref.parse_strict_v3_envelope(_envelope_for(case))

    content_key = ref.open_content_key(
        enc,
        wrapped,
        _b64d(case["recipientPrivateKeyRaw"]),
        _b64d(case["pinnedSenderPublicKeyX963"]),
        case["keyAAD"].encode(),
    )
    assert content_key == _b64d(case["plaintextContentKey"]), "unwrapped content key mismatch"

    payload = ref.open_payload_base64(
        case["payloadCiphertext"], content_key, case["payloadAAD"].encode()
    )
    assert payload.decode("utf-8") == case["payloadPlaintext"], "sealed payload mismatch"

    if case["kind"] in _EVENT_KINDS:
        _assert_strict_event_schema(case, payload)
    if case["kind"] in _JSON_DESTINATION_KINDS:
        _assert_destination_bound(case, payload)


def _assert_strict_event_schema(case, payload: bytes):
    """Mirror plugins/platforms/burnbar/adapter.py: a sealed inbound event the
    agent accepts MUST carry an authenticated destinationId and a non-negative
    replayCounter/eventCounter."""
    obj = json.loads(payload.decode("utf-8"))
    assert isinstance(obj.get("destinationId"), str) and obj["destinationId"], (
        f"{case['name']}: sealed event missing authenticated destinationId"
    )
    counters = [obj[k] for k in _REPLAY_KEYS if k in obj]
    assert counters, f"{case['name']}: sealed event missing replayCounter/eventCounter"
    assert all(isinstance(c, int) and c >= 0 for c in counters), (
        f"{case['name']}: replay counter must be a non-negative integer"
    )


def _assert_destination_bound(case, payload: bytes):
    obj = json.loads(payload.decode("utf-8"))
    assert obj.get("destinationId") == "burnbar:home", (
        f"{case['name']}: sealed JSON payload missing authenticated destinationId"
    )


# ---------------------------------------------------------------------------
# Negative cases: every mutation is rejected fail-closed
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("neg", NEGATIVES, ids=[c["name"] for c in NEGATIVES])
def test_negative_case_is_rejected(neg):
    base = CASES[neg["derivedFrom"]]
    envelope = _envelope_for(base)

    # Apply the structural mutations (downgrade / stripped marker / mutated bytes).
    if "relayKeyVersionOverride" in neg:
        envelope["relayKeyVersion"] = neg["relayKeyVersionOverride"]
    if neg.get("dropField"):
        envelope.pop(neg["dropField"], None)
    if "encOverride" in neg:
        envelope["enc"] = neg["encOverride"]
    if "wrappedKeyOverride" in neg:
        envelope["wrappedKey"] = neg["wrappedKeyOverride"]

    key_aad = neg.get("keyAADOverride", base["keyAAD"]).encode()
    recipient_priv = _b64d(neg.get("recipientPrivateKeyRawOverride", base["recipientPrivateKeyRaw"]))
    pinned_sender = _b64d(
        neg.get("pinnedSenderPublicKeyX963Override", base["pinnedSenderPublicKeyX963"])
    )

    # Tight per-negative expectation: assert the EXACT failure class the mutation
    # should produce. A broad tuple (incl. ValueError) would let a base64-decode
    # artifact (binascii.Error subclasses ValueError) masquerade as a real reject.
    expected_error = _EXPECTED_ERROR[neg["expectedError"]]
    with pytest.raises(expected_error):
        enc, wrapped = ref.parse_strict_v3_envelope(envelope)
        ref.open_content_key(enc, wrapped, recipient_priv, pinned_sender, key_aad)


_EXPECTED_ERROR = {
    "InvalidTag": InvalidTag,
    "HpkeError": ref.HpkeError,
    "RelayV3EnvelopeError": ref.RelayV3EnvelopeError,
}


def test_negative_cases_are_only_rejected_by_their_mutation():
    """Guard against a vacuous negative: the un-mutated base of every negative
    MUST open, so each rejection is caused by the mutation, not a broken base."""
    for neg in NEGATIVES:
        base = CASES[neg["derivedFrom"]]
        enc, wrapped = ref.parse_strict_v3_envelope(_envelope_for(base))
        content_key = ref.open_content_key(
            enc,
            wrapped,
            _b64d(base["recipientPrivateKeyRaw"]),
            _b64d(base["pinnedSenderPublicKeyX963"]),
            base["keyAAD"].encode(),
        )
        assert content_key == _b64d(base["plaintextContentKey"])


def _envelope_for(case: dict) -> dict:
    """The relay-visible sealed envelope fields for a case (a fresh dict each
    call so mutations never leak across cases)."""
    return {
        "relayKeyVersion": case["relayKeyVersion"],
        "relayEncryption": case["relayEncryption"],
        "enc": case["enc"],
        "wrappedKey": case["wrappedKey"],
        "senderPublicKey": case["senderPublicKeyX963"],
    }


# ---------------------------------------------------------------------------
# Coordination: cross-check the production relay_e2ee HPKE against the fixture
# ---------------------------------------------------------------------------


def _import_relay_e2ee():
    try:
        from gateway.crypto import relay_e2ee  # type: ignore
    except Exception as exc:  # pragma: no cover - import guard
        pytest.skip(f"gateway.crypto.relay_e2ee not importable ({exc!r})")
    return relay_e2ee


def test_production_hpke_primitives_match_reference():
    """The Python lane's relay_e2ee HPKE primitives must be byte-identical to the
    reference, so a fixture generated by the reference opens under production."""
    prod = _import_relay_e2ee()
    for attr in (
        "_HPKE_KEM_SUITE_ID",
        "_HPKE_SUITE_ID",
        "_HPKE_INFO_PREFIX",
        "_hpke_extract_and_expand",
        "_hpke_auth_key_schedule",
        "_hpke_info",
    ):
        if not hasattr(prod, attr):
            pytest.skip(f"relay_e2ee has no {attr} yet (Python v3 lane in progress)")

    assert prod._HPKE_KEM_SUITE_ID == ref._KEM_SUITE_ID
    assert prod._HPKE_SUITE_ID == ref._HPKE_SUITE_ID
    assert prod._HPKE_INFO_PREFIX == ref.INFO_PREFIX

    # Use production primitives to open a real fixture wrap (assemble AuthDecap
    # around the production KDF/schedule/info). If it recovers the content key,
    # the production HPKE math matches the canonical vectors.
    case = CASES["phone_event_text"]
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    enc = _b64d(case["enc"])
    sk_r = ref.private_from_raw(_b64d(case["recipientPrivateKeyRaw"]))
    pk_s = ref.public_from_x963(_b64d(case["pinnedSenderPublicKeyX963"]))
    pk_e = ref.public_from_x963(enc)
    dh = sk_r.exchange(ec.ECDH(), pk_e) + sk_r.exchange(ec.ECDH(), pk_s)
    kem_context = enc + ref.serialize_public(sk_r.public_key()) + ref.serialize_public(pk_s)
    shared = prod._hpke_extract_and_expand(dh, kem_context)
    key, base_nonce = prod._hpke_auth_key_schedule(shared, prod._hpke_info(case["keyAAD"].encode()))
    content_key = AESGCM(key).decrypt(base_nonce, _b64d(case["wrappedKey"]), case["keyAAD"].encode())
    assert content_key == _b64d(case["plaintextContentKey"]), (
        "production relay_e2ee HPKE primitives do not open the canonical v3 vector"
    )


def test_production_public_v3_open_parity():
    """relay_e2ee.unwrap_symmetric_key_v3 must open every positive fixture wrap to
    the expected content key (full production-path parity — production opens the
    independent reference's vectors)."""
    prod = _import_relay_e2ee()
    if not hasattr(prod, "unwrap_symmetric_key_v3"):
        pytest.skip(
            "relay_e2ee.unwrap_symmetric_key_v3 not present yet; Python lane owns it. "
            "Primitive-level parity is already asserted by "
            "test_production_hpke_primitives_match_reference."
        )

    for case in POSITIVES:
        content_key = prod.unwrap_symmetric_key_v3(
            case["enc"],
            case["wrappedKey"],
            _b64d(case["recipientPrivateKeyRaw"]),
            case["keyAAD"].encode(),
            pinned_sender_public=case["pinnedSenderPublicKeyX963"],
        )
        assert content_key == _b64d(case["plaintextContentKey"]), (
            f"{case['name']}: production unwrap_symmetric_key_v3 returned a different content key"
        )


def test_production_and_reference_v3_are_bidirectionally_interoperable():
    """The strongest cross-stream proof: production opens the reference's wraps
    AND the reference opens production's wraps, for the same keys/aad/key."""
    prod = _import_relay_e2ee()
    if not (hasattr(prod, "wrap_symmetric_key_v3") and hasattr(prod, "unwrap_symmetric_key_v3")):
        pytest.skip("relay_e2ee public v3 wrap/unwrap not both present yet; Python lane owns it.")

    keys = FIXTURE["keys"]
    recipient_priv = _b64d(keys["agentRecipientPrivateKeyRaw"])
    recipient_pub = _b64d(keys["agentRecipientPublicKeyX963"])
    sender_priv = _b64d(keys["phoneSenderPrivateKeyRaw"])
    sender_pub = _b64d(keys["phoneSenderPublicKeyX963"])
    key_aad = CASES["phone_event_text"]["keyAAD"].encode()
    content_key = bytes(range(1, 33))

    # reference wraps -> production opens
    ref_enc, ref_wrapped = ref.wrap_content_key(content_key, recipient_pub, sender_priv, key_aad)
    assert (
        prod.unwrap_symmetric_key_v3(
            ref_enc, ref_wrapped, recipient_priv, key_aad, pinned_sender_public=keys["phoneSenderPublicKeyX963"]
        )
        == content_key
    ), "production failed to open a reference-generated v3 wrap"

    # production wraps -> reference opens
    prod_wrap = prod.wrap_symmetric_key_v3(
        content_key, keys["agentRecipientPublicKeyX963"], key_aad, sender_private=sender_priv
    )
    assert (
        ref.open_content_key(prod_wrap.enc, prod_wrap.wrapped_key, recipient_priv, sender_pub, key_aad)
        == content_key
    ), "reference failed to open a production-generated v3 wrap"

    # the pinned-sender binding holds across implementations: a wrong pin fails.
    with pytest.raises(InvalidTag):
        prod.unwrap_symmetric_key_v3(
            ref_enc,
            ref_wrapped,
            recipient_priv,
            key_aad,
            pinned_sender_public=keys["agentRecipientPublicKeyX963"],  # wrong pin
        )


def test_downgrade_and_strip_fail_closed_in_production():
    """Prove the SHIPPED fail-closed behavior when a relay downgrades or strips a
    sealed v3 frame, against the REAL relay_e2ee openers (the adapter dispatches
    the supported {v2, v3} set by version; this exercises the openers it routes
    to). The security property: no older opener can extract the content key from
    the v3 bytes, and the v3 opener requires the exact HPKE marker."""
    prod = _import_relay_e2ee()
    for attr in (
        "unwrap_symmetric_key",
        "unwrap_symmetric_key_v3",
        "InvalidCiphertextError",
        "HPKE_ALGORITHM",
    ):
        if not hasattr(prod, attr):
            pytest.skip(f"relay_e2ee.{attr} not present yet; Python lane owns it.")

    base = CASES["phone_event_text"]
    recipient_priv = _b64d(base["recipientPrivateKeyRaw"])
    pinned = base["pinnedSenderPublicKeyX963"]
    key_aad = base["keyAAD"].encode()

    # Positive control: the v3 opener with correct params DOES recover the key.
    assert (
        prod.unwrap_symmetric_key_v3(
            base["enc"], base["wrappedKey"], recipient_priv, key_aad, pinned_sender_public=pinned
        )
        == _b64d(base["plaintextContentKey"])
    )

    # v3 -> v2 downgrade: production routes a relayKeyVersion=2 frame to the v2
    # opener, which fails closed because the 48-byte v3 wrappedKey is shorter than
    # the v2 minimum (enc(65) ‖ nonce(12) ‖ ct ‖ tag(16)). Key never recovered.
    assert len(_b64d(base["wrappedKey"])) == 48
    with pytest.raises(prod.InvalidCiphertextError):
        prod.unwrap_symmetric_key(
            base["wrappedKey"], recipient_priv, key_aad, sender_public_base64=pinned
        )

    # Even the v1 anonymous opener (no sender pin) fails closed on the v3 bytes,
    # so a v1 relabel can extract nothing either.
    with pytest.raises(prod.InvalidCiphertextError):
        prod.unwrap_symmetric_key(base["wrappedKey"], recipient_priv, key_aad)

    # Stripped/incorrect HPKE marker: the v3 dispatch requires the exact marker
    # (the adapter refuses a v3 frame whose relayEncryption != HPKE_ALGORITHM).
    assert base["relayEncryption"] == prod.HPKE_ALGORITHM
